on: [push]
name: PHPStan

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Run PHPSTAN
        run: vendor/bin/phpstan --memory-limit=-1
